Testing workflow

diff --git a/.github/workflows/gh_deploy.yaml b/.github/workflows/gh_deploy.yaml
--- a/.github/workflows/gh_deploy.yaml
+++ b/.github/workflows/gh_deploy.yaml
@@ -15,25 +15,26 @@ jobs:
             apt-get install git -y
             echo $(git --version)
             echo $(pwd)
+            cd $GITHUB_WORKSPACE
+            ls
       # - uses: actions/setup-python@v2
       - uses: actions/checkout@v2
-      - name: "Build demp"
+      - name: "Build demo"
         uses: ammaraskar/sphinx-action@master
         with:
-          docs-folder: demo/
+          docs-folder: "/github/workspace/demo/"
       
-      - name: "Commit build files"
-        run: echo https://github.com/$GITHUB_REPOSITORY.git
-        # run: |
-        #   git clone https://github.com/$GITHUB_REPOSITORY.git --branch gh-pages --single-branch gh-pages
-        #   cp -r docs/_build/html/* gh-pages/
-        #   cd gh-pages
-        #   git config --local user.email "action@github.com"
-        #   git config --local user.name "GitHub Action"
-        #   git add .
-        #   git commit -m "Update documentation" -a || true
-        #   # The above command will fail if no changes were present, so we ignore
-        #   # the return code.
+      # - name: "Commit build files"
+      #   run: |
+      #     git clone https://github.com/$GITHUB_REPOSITORY.git --branch gh-pages --single-branch gh-pages
+      #     cp -r docs/_build/html/* gh-pages/
+      #     cd gh-pages
+      #     git config --local user.email "action@github.com"
+      #     git config --local user.name "GitHub Action"
+      #     git add .
+      #     git commit -m "Update Demo Build" -a || true
+      #     # The above command will fail if no changes were present, so we ignore
+      #     # the return code.
       
       # - name: "Push build"
       #   uses: ad-m/github-push-action@master
